### PR TITLE
Implement IoT SQL encode function

### PR DESCRIPTION
**Pull request by ccatterina**
Despite of `encode(*, 'base64')` seemed to be supported (replacing it with the placeholder `*b64`) actually it didn’t work properly.

I refactored the fields evaluation in order to implement `encode` in the same way as the other sql functions.

### CODE REVIEW

**Comment by ccatterina** [comment]
Hi @whummer, what do you think about this?
We need this feature to use our topic rules on localstack.

**Comment by whummer** [comment]
Hi @ccatterina , many thanks for this PR, and apologies for the super long delay - unfortunately I totally missed the notification in this repo! The change looks good to me - but I think it would also be good to contribute this feature to the upstream repo in https://github.com/mitipi/serverless-iot-offline . 

Probably going to merge this PR now, and release a new version that also includes the latest commits from the upstream repo - but as mentioned, would be great if we could contribute these changes (and get some feedback on them) upstream, too..! 🙏 Thanks for your help and contribution!

**Comment by ccatterina** [comment]
Hi, don't worry for the delay.  
Anyway, I agree that we should contribute these changes to the upstream. Would you like me to send a new PR to the upstream repo or will you take care of it?
Thanks

**Comment by whummer** [comment]
If you could take care of it, that would be fantastic @ccatterina ! 🙌  We will then make sure to rebase this fork onto latest upstream `master`, and get it into LocalStack.. 👍

**Comment by ccatterina** [comment]
https://github.com/mitipi/serverless-iot-offline/pull/26

**Pull request merged**
